### ISSUE TITLE
Add validation for operator codes

### ISSUE THREAD

**Issue by davitovmasyan** [hrachocode/phoneregex#2]
It shouldn't match numbers with `00` or any other non-existing operator code.

Here is an example:

`000000000`

**Comment by hrachocode** [comment]
Updated repo took strict +374 OR 0 and also range of 1-9 in operator code , in other parts 0 is possble

example: +37499000000 << accepted
example: +37400000000  OR +00000000 OR +37099000000<<  NOT accepted
